project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!*.rmd"

website:
  title: "MET581 - R lecture material"
  repo-url: https://github.com/H-Mateus/MET581---Computing-for-Bioinformatics-and-Genetic-Epidemiology
  issue-url: https://github.com/H-Mateus/MET581---Computing-for-Bioinformatics-and-Genetic-Epidemiology/issues/new/choose
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - icon: github
        href: https://github.com/H-Mateus/MET581---Computing-for-Bioinformatics-and-Genetic-Epidemiology
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Programming in R"
        contents: 
          - text: "Slides"
            href: 06_Programming_in_R/met581_06_programming_in_r.qmd
          - text: "Workshop"
            href: 10_resources/01_workshop_answers/met581_programming_in_r_workshop_answers.qmd
      - section: "Data Visualisation in R"
        contents: 
          - text: "Slides"
            href: 07_Data_Visualisation_in_R/met581_07_data_visualisation_in_r.qmd
      - section: "Modelling in R"
        contents: 
          - text: "Slides"
            href: 08_Modelling_in_R/met581_08_modelling_r.qmd
          - text: "Practice"
            href: 08_Modelling_in_R/modelling_in_r_practice.qmd
      - section: "R Shiny"
        contents: 
          - text: "Code examples"
            href: 09_ShinyApp/met581_09_shiny_code_examples.qmd
          - text: "Code example solutions"
            href: 09_ShinyApp/met581_09_shiny_code_examples_answers.qmd
      
execute: 
  freeze: auto

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
